name: 'cloud-run-env-action'
description:
  'Appends the given environment variables from a .env file into your cloud run
  declaration'
author: 'hedge-video'

# Define your inputs here.
inputs:
  input:
    description: 'The input cloud run yaml file'
    required: true

  env_file:
    description: 'The .env file'
    required: true

  output:
    description: 'The output file path'

  container_name:
    description: 'The container name that will receive the env var'

# Define your outputs here.
outputs:
  output:
    description: 'The newly generated cloud run yaml file'

runs:
  using: node20
  main: dist/index.js
