apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-test-app
  labels:
    cloud.googleapis.com/location: ${MANIFEST_LOCATION}
spec:
  template:
    spec:
      serviceAccountName: ${MANIFEST_SERVICE_ACCOUNT}
      containers:
        - name: my-test-app
          image: ${MANIFEST_IMAGE}
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: MY_SUPER_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: MY_SUPER_SECRET

            - name: MY_APP_SPECIFIC_VARIABLE
              value: foo

            - name: MY_APP_INJECTED_VARIABLE
              value: ${MANIFEST_INJECTED_VARIABLE}
